# Generated by Django 5.0.6 on 2024-05-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
