# Generated by Django 3.2.18 on 2023-03-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myglory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GloryHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('proficiency', models.IntegerField()),
                ('proficiency_level', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=100)),
                ('speciality', models.CharField(max_length=20)),
                ('strong_period', models.CharField(max_length=20)),
                ('live_ability', models.IntegerField()),
                ('damage_ability', models.IntegerField()),
                ('difficulty', models.IntegerField()),
                ('passive_skill', models.CharField(max_length=100)),
                ('skill_1', models.CharField(max_length=100)),
                ('skill_2', models.CharField(max_length=100)),
                ('skill_3', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
