# Generated by Django 3.2.18 on 2023-03-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myglory', '0002_gloryhero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloryhero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
